apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: my-app
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      tier: frontend
  template:
    metadata:
      labels:
        app: my-app
        tier: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest


#kubectl apply -f deployment.yml

#kubectl get deployments

#kubectl rollout status deployment/myapp-deployment

#kubectl rollout history deployments




## Example of a Kubernetes Deployment YAML file--- sample
apiVersion: apps/v1
kind: Deployment  
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest