apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: my-app
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      tier: frontend
  template:
    metadata:
      labels:
        app: my-app
        tier: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest


# kubectl apply -f replicaset.yml
# kubectl get rs
# kubectl describe name


# Example of a Kubernetes Replicaset YAML file
apiVersion: apps/v1
kind: Replicaset
meatadata:
   name: my-replicaset
spec:
   replicas: 3
   selector:
      matchLabels:
         app: my-app
   template:
      metadata:
         labels:
            app: my-app
      spec:
         containers:
            - name: my-container
              image: nginx:latest

